### ISSUE TITLE
the background will be stretched

### ISSUE THREAD

**Issue by rongxianren** [dss886/Android-EmotionInputDetector#3]
if you add a background in the main layout xml file, when the soft keyboard show up the background pic will be stretched.  Every haven't be changed only add a background.   

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:background="@drawable/default_chat_scene"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".MainActivity">

**Comment by dss886** [comment]
This library will set the value of the activity's softInputMode as "AdjustResize", which means when soft-input keyboard shows, the height of the activity's content will be cut shorter, causing background stretched.

There are 2 ways to solve this problem:
1. Use background picture as a 9.png;
2. Set the scaleType of your background as "fitStart".
