### ISSUE TITLE
楼主,依赖无法添加,有aar文件吗?

### ISSUE THREAD

**Issue by eclipse4dk** [dss886/Android-EmotionInputDetector#4]
RT.依赖无法添加,请问有aar文件吗?

**Comment by dss886** [comment]
抱歉，目前只支持Gradle调用，暂时没有支持Eclipse的计划

**Comment by eclipse4dk** [comment]
好的,谢谢你了.

------------------ 原始邮件 ------------------
发件人: "dss886";notifications@github.com;
发送时间: 2016年11月8日(星期二) 下午4:23
收件人: "dss886/Android-EmotionInputDetector"Android-EmotionInputDetector@noreply.github.com; 
抄送: "丁可"547839603@qq.com; "Author"author@noreply.github.com; 
主题: Re: [dss886/Android-EmotionInputDetector] 楼主,依赖无法添加,有aar文件吗? (#4)

抱歉，目前只支持Gradle调用，暂时没有支持Eclipse的计划
