### ISSUE TITLE
进入界面不谈软键盘

### ISSUE THREAD

**Issue by merlin720** [dss886/Android-EmotionInputDetector#5]
EmotionKeyboard.java
public EmotionKeyboard build(){
	        //设置软件盘的模式：SOFT_INPUT_ADJUST_RESIZE  这个属性表示Activity的主窗口总是会被调整大小，从而保证软键盘显示空间。
	        //从而方便我们计算软件盘的高度
	        mActivity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN |
	                WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
	        //隐藏软件盘
	        showSoftInput();
	        return this;
	    }
EmotionKeyboard这个类的build方法里我设置软键盘弹出不管用，而且我在activity里直接强制弹出软键盘也会弹出一下就又隐藏了。麻烦看一下

**Comment by dss886** [comment]
既然要弹出软键盘，为什么要设置SOFT_INPUT_STATE_ALWAYS_HIDDEN？

**Comment by merlin720** [comment]
哈哈，就看注释了没认真看代码。可以谈软键盘了，多谢！
