### ISSUE TITLE
表情和文字一行的时候行高会变高

### ISSUE THREAD

**Issue by merlin720** [dss886/Android-EmotionInputDetector#6]
SpanStringUtils

public static SpannableString getEmotionContent(int emotion_map_type,final Context context, final TextView tv, String source) {
		SpannableString spannableString = new SpannableString(source);
		Resources res = context.getResources();

		String regexEmotion = "\\[([\u4e00-\u9fa5\\w])+\\]";
		Pattern patternEmotion = Pattern.compile(regexEmotion);
		Matcher matcherEmotion = patternEmotion.matcher(spannableString);

		while (matcherEmotion.find()) {
			// 获取匹配到的具体字符
			String key = matcherEmotion.group();
			// 匹配字符串的开始位置
			int start = matcherEmotion.start();
			// 利用表情名字获取到对应的图片
			Integer imgRes = EmotionUtils.getImgByName(emotion_map_type,key);
			if (imgRes != null) {
				// 压缩表情图片
				int size = (int) tv.getTextSize()*13/10;
				Bitmap bitmap = BitmapFactory.decodeResource(res, imgRes);
				Bitmap scaleBitmap = Bitmap.createScaledBitmap(bitmap, size, size, true);

				ImageSpan span = new ImageSpan(context, scaleBitmap);
				spannableString.setSpan(span, start, start + key.length(), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
			}
		}
		return spannableString;
	}
spannableString添加imageSpan的时候如果一行里边同时出现表情和文字的话就会出现行高变高的问题，纯文字 纯表情都不会，请问有没有好的解决方案。

**Comment by dss886** [comment]
来个截图？是同样的表情，有文字时行高要比纯表情高吗？

**Comment by merlin720** [comment]
给您发了个邮件只有一个截图，

**Comment by merlin720** [comment]
同样的表情，就是比如有三行a 纯文字，b纯表情，c文字+表情（表情为同一个表情），ab高度相同，c会大于 a的高度。不知道这样解释您可以看清楚么

**Comment by dss886** [comment]
你的问题跟本项目关系不大，建议去StackOverFlow上寻求帮助

**Comment by merlin720** [comment]
好的，确实是开发中遇到的小问题，就是想咨询一下，看您了解什么原因么，我去StackOverFlow上看一下
