### ISSUE TITLE
我在使用时，关键系统键盘的时候发现无法弹出扩展的布局了

### ISSUE THREAD

**Issue by gaobin881201** [dss886/Android-EmotionInputDetector#7]
我在使用时，关键系统键盘的时候发现无法弹出扩展的布局了

**Comment by dss886** [comment]
有截图或者相关代码吗

**Comment by gaobin881201** [comment]
你有qq或者微信的联系方式吗？这样沟通方便一点

发自我的 iPhone

**Comment by gaobin881201** [comment]
private int getSupportSoftInputHeight() {
        Rect r = new Rect();
        mActivity.getWindow().getDecorView().getWindowVisibleDisplayFrame(r);
        int screenHeight = mActivity.getWindow().getDecorView().getRootView().getHeight();
        int softInputHeight = screenHeight - r.bottom;
        //        if (Build.VERSION.SDK_INT >= 20) {
        //            // When SDK Level >= 20 (Android L), the softInputHeight will contain the height of softButtonsBar (if has)
        //            softInputHeight = softInputHeight + getSoftButtonsBarHeight();
        //        }
        if (softInputHeight < 0) {
            Log.w("EmotionKeyboard", "Warning: value of softInputHeight is below zero!");
        }
        if (softInputHeight > 0) {
            sp.edit().putInt(SHARE_PREFERENCE_TAG, softInputHeight).apply();
        }
        return softInputHeight;
    }
我在调用此方法时一直返回0

**Comment by dss886** [comment]
为什么要将 if (Build.VERSION.SDK_INT >= 20) { 这一段注释掉？
